### ISSUE TITLE
PayloadAuthenticationMiddleware Status code

### ISSUE THREAD

**Issue by valeriomazzeo** [vapor/jwt-provider#16]
Many clients rely on status codes `401` and `403` to understand whether they need to authenticate again or not.

`PayloadAuthenticationMiddleware` shouldn't just throw whatever error it receive from its components, but it should also ensure (like any other authentication middleware), that the status code is appropriate.

In general, it looks to me that any error about missing / invalid token or invalid jwt signature should throw a `401` error, meanwhile claims verification failure (with exception of `exp`) should throw a `403` error. 

Currently, I had to wrap the middleware in a `do / catch` and I had to apply this logic to ensure status codes are consistent.

```swift
private func abort(with error: Swift.Error) -> Swift.Error {

        switch error {

        case let error as JWTError:

            switch error {
            case .incorrectPayloadForClaimVerification,
                 .missingClaim,
                 .verificationFailedForClaim:

                return Abort(.forbidden, reason: error.description)

            default:
                return Abort(.unauthorized, reason: error.description)
            }

        /* Not needed anymore
        case let error as AuthenticationError:

            return Abort(
                .unauthorized,
                metadata: error.metadata,
                reason: error.reason,
                identifier: error.identifier,
                possibleCauses: error.possibleCauses,
                suggestedFixes: error.suggestedFixes,
                documentationLinks: error.documentationLinks,
                stackOverflowQuestions: error.stackOverflowQuestions,
                gitHubIssues: error.gitHubIssues
            )

        case let error as AuthorizationError:

            return Abort(
                .forbidden,
                metadata: error.metadata,
                reason: error.reason,
                identifier: error.identifier,
                possibleCauses: error.possibleCauses,
                suggestedFixes: error.suggestedFixes,
                documentationLinks: error.documentationLinks,
                stackOverflowQuestions: error.stackOverflowQuestions,
                gitHubIssues: error.gitHubIssues
            )
        */
        default:
            return error
        }
    }
```

It would be nice for `JWTProvider` to return consistent errors.

~~Note that fixing https://github.com/vapor/auth-provider/issues/14 will not make necessary the following two cases:~~

- ~~`case let error as AuthenticationError:`~~
- ~~`case let error as AuthorizationError:`~~

**Comment by tanner0101** [comment]
https://github.com/vapor/auth-provider/pull/18

**Comment by valeriomazzeo** [comment]
@tanner0101 This has been definitely improved by https://github.com/vapor/auth-provider/pull/18 but I am not sure is fixed yet.

Sending `Authorization: Bearer 123` returns:

```
HTTP/1.1 500 Internal Server Error
Content-Type: application/vnd.api+json
Content-Length: 153

{"links":{"self":"http:\/\/localhost:8080\/users"},"errors":[{"status":"500","detail":"The operation couldn’t be completed. (JWT.JWTError error 7.)"}]}
```

Now that's because the `JWT` error is propagated, in the specific case the jwt format is not correct and it can't parse the token.

As far as the `JWT Provider` is concerned, especially the `PayloadAuthenticationMiddleware`, those errors should not be leaked.

I propose that those errors are caught by the middleware that then can apply the proper status code to them, for example: 401 in this case.
