### ISSUE TITLE
Is it normal that the PayloadAuthenticationMiddle try to initialize the Model using its json initilizer?

### ISSUE THREAD

**Issue by patchthecode** [vapor/jwt-provider#21]
i used Postman to send a post request with the authenticated token inside the header.
Now, in my server app, I have a `PayloadAuthenticationMiddleware` setup (JWT middleware looking to see if request are authenticated)

When the request is sent, the function flow finally goes the `User` model class which i am trying to authenticate.

The problem is that, it is trying to create a `User` instance by using the `convenience init(json: JSON) throws` function. The JSON object that it is passing to that function is the _decoded payload_ of the JsonWebToken.

Is this how it supposed to be? or is this a bug.
My JWT’s payload only has the `email` of the user that I am trying to authenticate. It Does not have all of the user information that the `convenience init(json: JSON) throws` function needs, to initialize -> firstName, lastName, password, email, birthdate, etc etc etc

Therefore initialization fails -> therefore JWT authentication fails.
Its like its forcing me to have all the user information in the payload of the JWT.

The problem seems to be in the file `PayloadAuthenticationMiddleware.swift` file

```swift
 public func respond(to req: Request, chainingTo next: Responder) throws -> Response {
        // if the user has already been authenticated
        // by a previous middleware, continue
        if req.auth.isAuthenticated(U.self) {
            return try next.respond(to: req)
        }

        let jwt = try req.parseJWT()

        let signer = try self.signer(for: jwt)

        _ = try req.jwt(verifyUsing: signer, and: self.claims)

        // create Payload type from the raw payload
        let payload = try U.PayloadType.init(json: jwt.payload) // <----- HERE IS THE PROBLEM!!

        // Log the user in with an Identifier credential
        // This amounts to fetching the user from the DB
        let u = try U.authenticate(payload)
        req.auth.authenticate(u)

        return try next.respond(to: req)
    }
```

The following code seems to be problem.
```swift
let payload = try U.PayloadType.init(json: jwt.payload)
```

This tries to instantiate an object, with just the JWT payload.
The JWT payload only has this in its payload
```
{
   email: "test@test.com"
}
```

It does not have all of the parameters that the jsonInit function needs to properly initialize a User object like the following.
```swift
    let firstName: String
    let lastName: String
    let password: Bytes
    let email: String
    let birthdate: String
    let receiveEmails: Bool
```

Therefore, `PayloadAuthenticationMiddle` is forcing me to put all that information in the payload inorder to work. Is this expected?

I would prefer that it calls some other function
```
let payload = try U.PayloadType.init(payload: jwt.payload)
```

And then use protocols, to force the developer to conform to a protocol that require the following function
```swift
func model(for payload: json) -> Model {

}
```

Was the question clear?

**Comment by siemensikkema** [comment]
I replied to your question on Slack. I'll copy paste it here. Let me know if anything's unclear.

> The payload should not contain all the information of the user. Email is enough. The trick is to not use your User type as the PayloadType but some other type that can be used to load your user from the database.

> For example:
> ```
> extension User: PayloadAuthenticatable {
>     public struct UserIdentifier: JSONInitializable {
>         let id: Identifier
> 
>         public init(json: JSON) throws {
>             id = Identifier(try json.get(SubjectClaim.name) as Node)
>         }
>     }
> 
>     public typealias PayloadType = UserIdentifier
> 
>     public static func authenticate(_ payload: PayloadType) throws -> User {
>         guard let user = try User.find(payload.id) else {
>             throw Abort.notFound
>         }
> 
>         return user
>     }
> }
> ```

**Comment by siemensikkema** [comment]
In the case above, I identify the user in the JWT by id (using a SubjectClaim value but that's a detail). You could do the same but with email instead.

**Comment by patchthecode** [comment]
Thanks so much man. This makes sense. 
I wish documentation makes this clear, but i understand that it is a work in progress.
Good work thus far.
Closing this issue. I hop it helps others.
