### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by treaves** [vapor/jwt-provider#3]
Any example on how to use this?  I'd like to use JWT for my services.  Looking at the Auth from Vapor itself, I don't know why they have their own login with Vapor auth header.  Kinda defeats the purpose.  I'm just looking for an example that will pull a User on each request and attach to the request.

Also, why would the secrets not be added to source control?  ALL configuration should be under source control, period.  And configuring JWT is - well - configuration.

**Comment by siemensikkema** [comment]
This is a very new package. Please bear with us while we flesh out the API and provide documentation. Here's an example of how to use it:

```swift
import Auth
import Vapor
import VaporJWT

// use Ints as ids
extension Int: Credentials {}

// conform Node to payload
extension Node: Payload {
    public func makeCredentials() throws -> Credentials {
        guard let id = self["id"]?.int else {
            throw Abort.custom(
                status: .badRequest,
                message: "missing id")
        }
        return id
    }
}

let drop = Droplet()
try drop.addProvider(VaporJWT.Provider.self)

// pass all requests through our JWT login middleware
let loginMiddleware = LoginMiddleware(
    signer: try drop.jwtSigner(),
    payloadType: Node.self)
drop.middleware.append(loginMiddleware)

// use protect middleware to check for valid user
let credentialError = Abort.custom(
    status: .forbidden,
    message: "Invalid credentials")
let protect = ProtectMiddleware(error: credentialError)

// require valid user for requests to "/"
drop.grouped(protect).get { req in
    "Protected"
}

drop.run()
```

If used with the following (not-recommended!) `jwt.json`:
```
{
    "signer": {
        "type": "unsigned"
    }
}
```

and a request with `Authorization` header: `Bearer eyJhbGciOiAibm9uZSIsInR5cCI6ICJKV1QifQ==.eyJpZCI6ICIxIiwibmFtZSI6ICJKb2huIERvZSJ9.ZTUwYWQ2Mzg4NDU0MmYzNWJkMWM0YjVkNjlkYWYxODFiYWZlZTA5MjBmOGM3MGEyMTEwYWU3NGM3ODFkMzRhOQ==` this will use Turnstile to try to authenticate using the credential `1`. This will fail but is outside the scope of `JWT`.

The `jwt.json` file contains the key which which JWTs can be read and/or signed. This is way too sensitive information to be left under source control in plain text where it will be shared with GitHub and any collaborators on your project.

See: https://vapor.github.io/documentation/guide/config.html.

**Comment by tanner0101** [comment]
@treaves once the 1.0 tag is released we will put up the documentation under docs.vapor.codes, including examples.

**Comment by Alex293** [comment]
Any timeline for this ? I'm building an API that require son token and this provider seems to be a nice way to start !

**Comment by siemensikkema** [comment]
@Alex293 no timeline unfortunately (that I know of) but you're welcome to ask to join us on Slack if you have any questions
