### ISSUE TITLE
Can't add to Packages.swift

### ISSUE THREAD

**Issue by treaves** [vapor/jwt-provider#4]
When added, and running vapor Xcode, these errors are produced:
Check your dependencies' Package.swift files to see where the conflict is.
Error: warning: refname '0.2.0' is ambiguous.
warning: refname '0.2.0' is ambiguous.
warning: refname '0.8.0' is ambiguous.
warning: refname '0.8.0' is ambiguous.
swift-package: error: The dependency graph could not be satisfied (https://github.com/vapor/vapor.git)

**Comment by siemensikkema** [comment]
This package depends on an alpha version of Vapor so to use it your project would also need to do so:

`.Package(url: "https://github.com/vapor/vapor.git", Version(2, 0, 0, prereleaseIdentifiers: ["alpha"]))`

**Comment by tanner0101** [comment]
This package hasn't been tagged 1.0 yet so use it at your own discretion.

FYI, you can check out the `Package.swift` files in any SPM package to see what it depends on. If that aligns with what your package and its dependencies use there should be no issues.

https://github.com/vapor/jwt-provider/blob/master/Package.swift

This has worked for me:

```swift
    dependencies: [
        .Package(url: "https://github.com/vapor/vapor.git", Version(2,0,0, prereleaseIdentifiers: ["alpha"])),
        .Package(url: "https://github.com/vapor/jwt-provider.git", majorVersion: 0, minor: 2)
    ],
```
