### ISSUE TITLE
Enable configurable encoding

### ISSUE THREAD

**Issue by siemensikkema** [vapor/jwt-provider#5]
Currently the default JWT encoding (Base64) is used. We'll need a way to configure the encoding that is used. A quite common use case is Base64URL encoding. Ideally we would be able to specify this in the `jwt.json` file.

**Comment by tanner0101** [comment]
Is this possible to specify in JWT right now or does that API need to be added as well?

**Comment by siemensikkema** [comment]
That's already possible:

```swift
    public init(
        token: String,
        encoding: Encoding = Base64Encoding()
    ) throws {
...
```
The other initializers also accept an `encoding` parameter.

**Comment by tanner0101** [comment]
[RFC 7519](https://tools.ietf.org/html/rfc7519) says JWT requires Base64 URL encoding. The option for different encodings was removed from the underlying JWT lib a while back. Closing this here now.
